### ISSUE TITLE
sync_items.complete() not working

### ISSUE THREAD

**Issue by garyking** [h6y3/todoist-ruby#2] opened 2018-04-09 20:35 UTC
For some reason, this method doesn't work at all.

**Comment by h6y3** [comment] 2018-10-11 22:35
I was not able to reproduce this issue.  Are you using the complete method like the way the unit test uses it here?  https://github.com/h6y3/todoist-ruby/blob/562521ca448f5638ea0d6b150b1bebdcf8097620/spec/items_spec.rb

**Comment by h6y3** [comment] 2018-10-11 22:35
Closing for now until I get repro

**Closed as completed by h6y3** 2018-10-11 22:35 UTC
